const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let state={user:JSON.parse(localStorage.getItem('bp_user')||'null'),records:JSON.parse(localStorage.getItem('bp_records')||'[]'),bodyRecords:JSON.parse(localStorage.getItem('bp_body_records')||'[]')}; let isSignup=false;
const save=()=>{localStorage.setItem('bp_user',JSON.stringify(state.user));localStorage.setItem('bp_records',JSON.stringify(state.records));localStorage.setItem('bp_body_records',JSON.stringify(state.bodyRecords))};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function renderAuth(){if(state.user){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=state.user.name;$('#profileName').textContent=state.user.name;$('#avatar').textContent=state.user.name[0]||'友';renderAll()}else{$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden')}}
$('#toggleAuth').onclick=()=>{isSignup=!isSignup;$('#authTitle').textContent=isSignup?'建立你的帳戶':'登入你的帳戶';$('#authSubtitle').textContent=isSignup?'建立一個專屬你的健康紀錄。':'每天一點記錄，讓健康更有跡可循。';$('#nameField').classList.toggle('hidden',!isSignup);$('#authSubmit').textContent=isSignup?'註冊並開始':'登入';$('#toggleAuth').innerHTML=isSignup?'已經有帳戶？ <strong>返回登入</strong>':'還沒有帳戶？ <strong>立即註冊</strong>'};
$('#authForm').onsubmit=e=>{e.preventDefault();const name=$('#nameInput').value.trim()||'朋友';const email=$('#emailInput').value.trim();if(!email)return;if(isSignup){state.user={name,email};state.records=[];save();toast('帳戶建立完成，歡迎你！')}else{state.user={name:state.user?.email===email?state.user.name:(email.split('@')[0]||'朋友'),email};save();toast('登入成功')}renderAuth()};
$('#logoutBtn').onclick=()=>{state.user=null;localStorage.removeItem('bp_user');renderAuth()};
function openModal(){$('#uploadModal').classList.remove('hidden');$('#scanStatus').classList.add('hidden');$('#preview').classList.add('hidden');$('#photoInput').value='';['sysInput','diaInput','pulseInput'].forEach(id=>$('#'+id).value='')}
function closeModal(){$('#uploadModal').classList.add('hidden')};$$('[data-open-upload]').forEach(b=>b.onclick=openModal);$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);
$('#photoInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=ev=>{$('#preview').src=ev.target.result;$('#preview').classList.remove('hidden');$('#dropZone strong').textContent=file.name;$('#dropZone span').textContent='照片已載入，正在辨識…';$('#scanStatus').classList.remove('hidden');setTimeout(()=>{const demo=[['120','80','72'],['128','82','76'],['116','75','68']][Math.floor(Math.random()*3)];$('#sysInput').value=demo[0];$('#diaInput').value=demo[1];$('#pulseInput').value=demo[2];$('#scanStatus').textContent='✓ 辨識完成，請確認下方數值後儲存';$('#dropZone span').textContent='可重新選擇照片';},850)};reader.readAsDataURL(file)};
$('#saveRecord').onclick=()=>{const sys=+$('#sysInput').value,dia=+$('#diaInput').value,pulse=+$('#pulseInput').value;if(!sys||!dia||!pulse){toast('請確認三項數值都已填寫');return}state.records.unshift({id:Date.now(),date:new Date().toISOString(),sys,dia,pulse});save();closeModal();renderAll();toast('這次測量已儲存')};
$$('.nav-item').forEach(b=>b.onclick=()=>showSection(b.dataset.section));$$('[data-section-link]').forEach(b=>b.onclick=()=>showSection(b.dataset.sectionLink));function showSection(name){$$('.content-section').forEach(x=>x.classList.add('hidden'));$('#'+name+'Section').classList.remove('hidden');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.section===name));if(name==='overview'||name==='records'||name==='body')renderCharts()}
function fmt(d){return new Date(d).toLocaleDateString('zh-TW',{month:'numeric',day:'numeric'})}function time(d){return new Date(d).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}function displayMemberName(name){return({爸爸:'春林',阿公:'春林',媽媽:'幼蘭',阿嬤:'幼蘭',哥哥:'盧大寶',老爸:'盧大寶',哥哥老婆:'戈小寶',老媽:'戈小寶',老大:'盧小豬',老二:'盧小珊',盧小胖:'盧小珊',老三:'盧小白',老四:'盧小龍'})[name]||name}
function renderLatest(){const r=state.records[0];if(!r){$('#latestCards').innerHTML='<div class="metric-card"><span class="metric-label">尚未有測量</span><strong>—</strong><small>上傳第一筆紀錄吧</small></div>';return}$('#latestCards').innerHTML=[['sys','高壓 SYS',r.sys,'mmHg','↗'],['dia','低壓 DIA',r.dia,'mmHg','↘'],['pulse','脈搏 PUL',r.pulse,'bpm','♥']].map(x=>`<div class="metric-card ${x[0]}"><span class="metric-label">${x[1]}</span><i class="metric-icon">${x[4]}</i><strong>${x[2]}</strong><small>${x[3]} ・ ${fmt(r.date)} ${time(r.date)}</small></div>`).join('')}
function renderRecords(){const el=$('#recordsList');if(!state.records.length){el.innerHTML='<div class="empty-records">還沒有血壓紀錄<br><button class="link-btn" data-open-upload>上傳第一筆照片 →</button></div>';el.querySelector('[data-open-upload]').onclick=openModal;return}el.innerHTML=state.records.map(r=>`<div class="record-row"><div class="record-date"><strong>${r.memberName?`${displayMemberName(r.memberName)} · `:''}${fmt(r.date)}</strong><small>${time(r.date)}</small></div><div class="record-value"><span>SYS</span>${r.sys}</div><div class="record-value"><span>DIA</span>${r.dia}</div><div class="record-value"><span>PUL</span>${r.pulse}</div><button class="delete-btn" data-id="${r.id}" title="刪除">×</button></div>`).join('');$$('.delete-btn').forEach(b=>b.onclick=()=>{state.records=state.records.filter(r=>r.id!=b.dataset.id);save();renderAll();toast('已刪除這筆紀錄')})}
function renderBodyRecords(){const latest=state.bodyRecords[0],metrics=$('#latestBodyMetrics'),list=$('#bodyRecordsList');if(!latest){metrics.innerHTML='<strong>—</strong><span>尚未有身高體重紀錄</span>';list.innerHTML='<div class="empty-records">還沒有身高體重紀錄</div>';return}const bmi=latest.bmi??(latest.weight/((latest.height/100)**2));metrics.innerHTML=`<div><strong>${latest.height}</strong><span>公分</span></div><div><strong>${latest.weight}</strong><span>公斤</span></div><div><strong>${Number(bmi).toFixed(1)}</strong><span>BMI</span></div>`;list.innerHTML=state.bodyRecords.map(r=>{const v=r.bmi??(r.weight/((r.height/100)**2));return `<div class="body-record-row"><div class="record-date"><strong>${r.memberName?`${displayMemberName(r.memberName)} · `:''}${fmt(r.date)}</strong><small>${time(r.date)}</small></div><div class="record-value"><span>身高</span>${r.height} cm</div><div class="record-value"><span>體重</span>${r.weight} kg</div><div class="record-value"><span>BMI</span>${Number(v).toFixed(1)}</div></div>`}).join('')}
function draw(canvas,items,emptyId='emptyChart'){const c=canvas.getContext('2d'),w=canvas.width=canvas.clientWidth*2,h=canvas.height=canvas.clientHeight*2;c.scale(2,2);const W=canvas.clientWidth,H=canvas.clientHeight,empty=$('#'+emptyId);c.clearRect(0,0,W,H);if(items.length<2){empty.classList.remove('hidden');return}empty.classList.add('hidden');const pad=30, vals=items.flatMap(r=>[r.sys,r.dia]),min=Math.min(...vals)-10,max=Math.max(...vals)+10; c.strokeStyle='#edf2f1';c.lineWidth=1;for(let i=0;i<4;i++){let y=pad+(H-pad*1.5)*i/3;c.beginPath();c.moveTo(pad,y);c.lineTo(W-pad,y);c.stroke()}[['sys','#f39b6d'],['dia','#6d9bdb']].forEach(([key,color])=>{c.strokeStyle=color;c.lineWidth=2.5;c.beginPath();items.forEach((r,i)=>{let x=pad+(W-pad*2)*i/(items.length-1),y=pad+(H-pad*1.5)*(1-(r[key]-min)/(max-min));i?c.lineTo(x,y):c.moveTo(x,y);c.fillStyle=color;c.fillRect(x-3,y-3,6,6)});c.stroke()});c.fillStyle='#a1afbd';c.font='11px DM Sans';items.forEach((r,i)=>{let x=pad+(W-pad*2)*i/(items.length-1);c.fillText(fmt(r.date),x-12,H-5)})}
function drawBodyTrend(){const canvas=$('#bodyTrendCanvas'),items=[...state.bodyRecords].slice(0,30).reverse(),empty=$('#emptyBodyChart'),c=canvas.getContext('2d'),W=canvas.clientWidth,H=canvas.clientHeight;c.canvas.width=W*2;c.canvas.height=H*2;c.scale(2,2);c.clearRect(0,0,W,H);if(items.length<2){empty.classList.remove('hidden');return}empty.classList.add('hidden');const left=43,right=43,top=24,bottom=30,plotW=W-left-right,plotH=H-top-bottom,range=key=>{const values=items.map(r=>Number(r[key]));const min=Math.min(...values),max=Math.max(...values),pad=Math.max((max-min)*.3,key==='height'?1:2);return[min-pad,max+pad]},weightRange=range('weight'),heightRange=range('height'),x=i=>left+plotW*i/(items.length-1),y=(v,r)=>top+plotH*(1-(v-r[0])/(r[1]-r[0]));c.strokeStyle='#edf2f1';c.lineWidth=1;for(let i=0;i<4;i++){const lineY=top+plotH*i/3;c.beginPath();c.moveTo(left,lineY);c.lineTo(W-right,lineY);c.stroke()}const series=[['weight',weightRange,'#2d9c9a'],['height',heightRange,'#6d9bdb']];series.forEach(([key,r,color])=>{c.strokeStyle=color;c.lineWidth=2.5;c.beginPath();items.forEach((item,i)=>{const px=x(i),py=y(Number(item[key]),r);i?c.lineTo(px,py):c.moveTo(px,py);c.fillStyle=color;c.fillRect(px-3,py-3,6,6)});c.stroke()});c.font='10px DM Sans';c.fillStyle='#2d9c9a';c.fillText(`${weightRange[1].toFixed(1)} kg`,2,top+4);c.fillText(`${weightRange[0].toFixed(1)} kg`,2,H-bottom);c.fillStyle='#6d9bdb';c.fillText(`${heightRange[1].toFixed(1)} cm`,W-right+4,top+4);c.fillText(`${heightRange[0].toFixed(1)} cm`,W-right+4,H-bottom);c.fillStyle='#a1afbd';items.forEach((item,i)=>{const px=x(i);c.fillText(fmt(item.date),px-12,H-5)})}
function renderCharts(){const items=[...state.records].slice(0,7).reverse();draw($('#trendCanvas'),items);draw($('#longCanvas'),[...state.records].slice(0,30).reverse(),'emptyLongChart');drawBodyTrend()}
function renderInsights(){const rs=state.records;if(!rs.length)return;[['avgSys','sys'],['avgDia','dia'],['avgPulse','pulse']].forEach(([id,k])=>$('#'+id).textContent=Math.round(rs.reduce((a,r)=>a+r[k],0)/rs.length))}
function renderAll(){renderLatest();renderRecords();renderBodyRecords();renderInsights();renderCharts()}

$('#bodyRecordForm').onsubmit=e=>{e.preventDefault();const height=+$('#heightInput').value,weight=+$('#weightInput').value;if(!height||!weight){toast('請輸入身高和體重');return}state.bodyRecords.unshift({id:Date.now(),date:new Date().toISOString(),height,weight,bmi:weight/((height/100)**2)});save();$('#bodyRecordForm').reset();renderAll();toast('身高體重已儲存')};

async function runBloodPressureOCR(dataUrl){
  if(!window.Tesseract) throw new Error('OCR library unavailable');
  const image=new Image(); image.src=dataUrl; await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject});
  const canvas=document.createElement('canvas'), ctx=canvas.getContext('2d'); const scale=2;
  canvas.width=image.width*scale; canvas.height=image.height*scale; ctx.filter='grayscale(1) contrast(1.8)'; ctx.drawImage(image,0,0,canvas.width,canvas.height);
  const crop=document.createElement('canvas'), cropCtx=crop.getContext('2d');
  const sx=Math.floor(canvas.width*.38), sy=Math.floor(canvas.height*.27), sw=Math.floor(canvas.width*.43), sh=Math.floor(canvas.height*.44);
  crop.width=sw; crop.height=sh; cropCtx.drawImage(canvas,sx,sy,sw,sh,0,0,sw,sh);
  const result=await Tesseract.recognize(crop,'eng',{logger:m=>{if(m.status==='recognizing text') $('#scanStatus').textContent=`✦ OCR 辨識中 ${Math.round((m.progress||0)*100)}%…`},tessedit_pageseg_mode:6,tessedit_char_whitelist:'0123456789'});
  const nums=(result.data.text.match(/\d{2,3}/g)||[]).map(Number).filter(n=>n>=30&&n<=300); const unique=[]; nums.forEach(n=>{if(!unique.includes(n))unique.push(n)});
  const sys=unique.find(n=>n>=90&&n<=220), dia=unique.find(n=>n>=40&&n<=140&&n!==sys), pulse=unique.find(n=>n>=40&&n<=180&&n!==sys&&n!==dia);
  if(sys) $('#sysInput').value=sys; if(dia) $('#diaInput').value=dia; if(pulse) $('#pulseInput').value=pulse; return {sys,dia,pulse};
}

$('#photoInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async ev=>{$('#preview').src=ev.target.result;$('#preview').classList.remove('hidden');$('#dropZone strong').textContent=file.name;$('#dropZone span').textContent='照片已載入，正在讀取螢幕區域…';$('#scanStatus').classList.remove('hidden');try{const out=await runBloodPressureOCR(ev.target.result);if(out.sys&&out.dia&&out.pulse){$('#scanStatus').textContent=`✓ 已辨識 ${out.sys} / ${out.dia} mmHg，脈搏 ${out.pulse}；請確認後儲存`;}else{$('#scanStatus').textContent='⚠ 照片辨識不完整，請手動確認或補上空白欄位';}}catch(err){console.error(err);$('#scanStatus').textContent='⚠ 無法完成辨識，請手動輸入照片上的數值';}$('#dropZone span').textContent='可重新拍照或選擇另一張照片';};reader.readAsDataURL(file)};
renderAuth();window.addEventListener('resize',renderCharts);
