const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let state={user:JSON.parse(localStorage.getItem('bp_user')||'null'),records:JSON.parse(localStorage.getItem('bp_records')||'[]')}; let isSignup=false;
const save=()=>{localStorage.setItem('bp_user',JSON.stringify(state.user));localStorage.setItem('bp_records',JSON.stringify(state.records))};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function renderAuth(){if(state.user){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=state.user.name;$('#profileName').textContent=state.user.name;$('#avatar').textContent=state.user.name[0]||'友';renderAll()}else{$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden')}}
$('#toggleAuth').onclick=()=>{isSignup=!isSignup;$('#authTitle').textContent=isSignup?'建立你的帳戶':'登入你的帳戶';$('#authSubtitle').textContent=isSignup?'建立一個專屬你的健康紀錄。':'每天一點記錄，讓健康更有跡可循。';$('#nameField').classList.toggle('hidden',!isSignup);$('#authSubmit').textContent=isSignup?'註冊並開始':'登入';$('#toggleAuth').innerHTML=isSignup?'已經有帳戶？ <strong>返回登入</strong>':'還沒有帳戶？ <strong>立即註冊</strong>'};
$('#authForm').onsubmit=e=>{e.preventDefault();const name=$('#nameInput').value.trim()||'朋友';const email=$('#emailInput').value.trim();if(!email)return;if(isSignup){state.user={name,email};state.records=[];save();toast('帳戶建立完成，歡迎你！')}else{state.user={name:state.user?.email===email?state.user.name:(email.split('@')[0]||'朋友'),email};save();toast('登入成功')}renderAuth()};
$('#logoutBtn').onclick=()=>{state.user=null;localStorage.removeItem('bp_user');renderAuth()};
function openModal(){$('#uploadModal').classList.remove('hidden');$('#scanStatus').classList.add('hidden');$('#preview').classList.add('hidden');$('#photoInput').value='';['sysInput','diaInput','pulseInput'].forEach(id=>$('#'+id).value='')}
function closeModal(){$('#uploadModal').classList.add('hidden')};$$('[data-open-upload]').forEach(b=>b.onclick=openModal);$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);
$('#photoInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=ev=>{$('#preview').src=ev.target.result;$('#preview').classList.remove('hidden');$('#dropZone strong').textContent=file.name;$('#dropZone span').textContent='照片已載入，正在辨識…';$('#scanStatus').classList.remove('hidden');setTimeout(()=>{const demo=[['120','80','72'],['128','82','76'],['116','75','68']][Math.floor(Math.random()*3)];$('#sysInput').value=demo[0];$('#diaInput').value=demo[1];$('#pulseInput').value=demo[2];$('#scanStatus').textContent='✓ 辨識完成，請確認下方數值後儲存';$('#dropZone span').textContent='可重新選擇照片';},850)};reader.readAsDataURL(file)};
$('#saveRecord').onclick=()=>{const sys=+$('#sysInput').value,dia=+$('#diaInput').value,pulse=+$('#pulseInput').value;if(!sys||!dia||!pulse){toast('請確認三項數值都已填寫');return}state.records.unshift({id:Date.now(),date:new Date().toISOString(),sys,dia,pulse});save();closeModal();renderAll();toast('這次測量已儲存')};
$$('.nav-item').forEach(b=>b.onclick=()=>showSection(b.dataset.section));$$('[data-section-link]').forEach(b=>b.onclick=()=>showSection(b.dataset.sectionLink));function showSection(name){$$('.content-section').forEach(x=>x.classList.add('hidden'));$('#'+name+'Section').classList.remove('hidden');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.section===name));if(name==='overview'||name==='insights')renderCharts()}
function fmt(d){return new Date(d).toLocaleDateString('zh-TW',{month:'numeric',day:'numeric'})}function time(d){return new Date(d).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}
function renderLatest(){const r=state.records[0];if(!r){$('#latestCards').innerHTML='<div class="metric-card"><span class="metric-label">尚未有測量</span><strong>—</strong><small>上傳第一筆紀錄吧</small></div>';return}$('#latestCards').innerHTML=[['sys','高壓 SYS',r.sys,'mmHg','↗'],['dia','低壓 DIA',r.dia,'mmHg','↘'],['pulse','脈搏 PUL',r.pulse,'bpm','♥']].map(x=>`<div class="metric-card ${x[0]}"><span class="metric-label">${x[1]}</span><i class="metric-icon">${x[4]}</i><strong>${x[2]}</strong><small>${x[3]} ・ ${fmt(r.date)} ${time(r.date)}</small></div>`).join('')}
function renderRecords(){const el=$('#recordsList');if(!state.records.length){el.innerHTML='<div class="empty-records">還沒有測量紀錄<br><button class="link-btn" data-open-upload>上傳第一筆照片 →</button></div>';el.querySelector('[data-open-upload]').onclick=openModal;return}el.innerHTML=state.records.map(r=>`<div class="record-row"><div class="record-date"><strong>${r.memberName?`${r.memberName} · `:''}${fmt(r.date)}</strong><small>${time(r.date)}</small></div><div class="record-value"><span>SYS</span>${r.sys}</div><div class="record-value"><span>DIA</span>${r.dia}</div><div class="record-value"><span>PUL</span>${r.pulse}</div><button class="delete-btn" data-id="${r.id}" title="刪除">×</button></div>`).join('');$$('.delete-btn').forEach(b=>b.onclick=()=>{state.records=state.records.filter(r=>r.id!=b.dataset.id);save();renderAll();toast('已刪除這筆紀錄')})}
function draw(canvas,items){const c=canvas.getContext('2d'),w=canvas.width=canvas.clientWidth*2,h=canvas.height=canvas.clientHeight*2;c.scale(2,2);const W=canvas.clientWidth,H=canvas.clientHeight;c.clearRect(0,0,W,H);if(items.length<2){$('#emptyChart').classList.remove('hidden');return}$('#emptyChart').classList.add('hidden');const pad=30, vals=items.flatMap(r=>[r.sys,r.dia]),min=Math.min(...vals)-10,max=Math.max(...vals)+10; c.strokeStyle='#edf2f1';c.lineWidth=1;for(let i=0;i<4;i++){let y=pad+(H-pad*1.5)*i/3;c.beginPath();c.moveTo(pad,y);c.lineTo(W-pad,y);c.stroke()}[['sys','#f39b6d'],['dia','#6d9bdb']].forEach(([key,color])=>{c.strokeStyle=color;c.lineWidth=2.5;c.beginPath();items.forEach((r,i)=>{let x=pad+(W-pad*2)*i/(items.length-1),y=pad+(H-pad*1.5)*(1-(r[key]-min)/(max-min));i?c.lineTo(x,y):c.moveTo(x,y);c.fillStyle=color;c.fillRect(x-3,y-3,6,6)});c.stroke()});c.fillStyle='#a1afbd';c.font='11px DM Sans';items.forEach((r,i)=>{let x=pad+(W-pad*2)*i/(items.length-1);c.fillText(fmt(r.date),x-12,H-5)})}
function renderCharts(){const items=[...state.records].slice(0,7).reverse();draw($('#trendCanvas'),items);draw($('#longCanvas'),[...state.records].slice(0,12).reverse())}
function renderInsights(){const rs=state.records;if(!rs.length)return;[['avgSys','sys'],['avgDia','dia'],['avgPulse','pulse']].forEach(([id,k])=>$('#'+id).textContent=Math.round(rs.reduce((a,r)=>a+r[k],0)/rs.length))}
function renderAll(){renderLatest();renderRecords();renderInsights();renderCharts()}

async function runBloodPressureOCR(dataUrl){
  if(!window.Tesseract) throw new Error('OCR library unavailable');
  const image=new Image(); image.src=dataUrl; await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject});
  const canvas=document.createElement('canvas'), ctx=canvas.getContext('2d'); const scale=2;
  canvas.width=image.width*scale; canvas.height=image.height*scale; ctx.filter='grayscale(1) contrast(1.8)'; ctx.drawImage(image,0,0,canvas.width,canvas.height);
  const crop=document.createElement('canvas'), cropCtx=crop.getContext('2d');
  const sx=Math.floor(canvas.width*.38), sy=Math.floor(canvas.height*.27), sw=Math.floor(canvas.width*.43), sh=Math.floor(canvas.height*.44);
  crop.width=sw; crop.height=sh; cropCtx.drawImage(canvas,sx,sy,sw,sh,0,0,sw,sh);
  const result=await Tesseract.recognize(crop,'eng',{logger:m=>{if(m.status==='recognizing text') $('#scanStatus').textContent=`✦ OCR 辨識中 ${Math.round((m.progress||0)*100)}%…`},tessedit_pageseg_mode:6,tessedit_char_whitelist:'0123456789'});
  const nums=(result.data.text.match(/\d{2,3}/g)||[]).map(Number).filter(n=>n>=30&&n<=300); const unique=[]; nums.forEach(n=>{if(!unique.includes(n))unique.push(n)});
  const sys=unique.find(n=>n>=90&&n<=220), dia=unique.find(n=>n>=40&&n<=140&&n!==sys), pulse=unique.find(n=>n>=40&&n<=180&&n!==sys&&n!==dia);
  if(sys) $('#sysInput').value=sys; if(dia) $('#diaInput').value=dia; if(pulse) $('#pulseInput').value=pulse; return {sys,dia,pulse};
}

$('#photoInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async ev=>{$('#preview').src=ev.target.result;$('#preview').classList.remove('hidden');$('#dropZone strong').textContent=file.name;$('#dropZone span').textContent='照片已載入，正在讀取螢幕區域…';$('#scanStatus').classList.remove('hidden');try{const out=await runBloodPressureOCR(ev.target.result);if(out.sys&&out.dia&&out.pulse){$('#scanStatus').textContent=`✓ 已辨識 ${out.sys} / ${out.dia} mmHg，脈搏 ${out.pulse}；請確認後儲存`;}else{$('#scanStatus').textContent='⚠ 照片辨識不完整，請手動確認或補上空白欄位';}}catch(err){console.error(err);$('#scanStatus').textContent='⚠ 無法完成辨識，請手動輸入照片上的數值';}$('#dropZone span').textContent='可重新拍照或選擇另一張照片';};reader.readAsDataURL(file)};
var bloodPressureCameraStream=null;
function stopBloodPressureCamera(){if(bloodPressureCameraStream){bloodPressureCameraStream.getTracks().forEach(track=>track.stop());bloodPressureCameraStream=null}$('#cameraPanel').classList.add('hidden')}
$('#openCameraBtn').onclick=async()=>{if(!navigator.mediaDevices?.getUserMedia){toast('此瀏覽器不支援直接相機拍攝，請改用上傳照片');return}try{bloodPressureCameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('#cameraVideo').srcObject=bloodPressureCameraStream;$('#cameraPanel').classList.remove('hidden')}catch(err){console.error(err);toast('無法開啟相機，請確認已允許瀏覽器使用相機') }};
$('#cancelCameraBtn').onclick=stopBloodPressureCamera;
$('#captureCameraBtn').onclick=()=>{const video=$('#cameraVideo');if(!video.videoWidth){toast('相機尚未準備完成');return}const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{const photo=new File([blob],`blood-pressure-${Date.now()}.jpg`,{type:'image/jpeg'});const dataTransfer=new DataTransfer();dataTransfer.items.add(photo);$('#photoInput').files=dataTransfer.files;$('#photoInput').dispatchEvent(new Event('change',{bubbles:true}));stopBloodPressureCamera()},'image/jpeg',.92)};
$$('[data-close-modal]').forEach(button=>button.addEventListener('click',stopBloodPressureCamera));
renderAuth();window.addEventListener('resize',renderCharts);
