-- 在 Supabase Dashboard > SQL Editor 執行一次
create table if not exists public.measurements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  systolic integer not null check (systolic between 50 and 300),
  diastolic integer not null check (diastolic between 30 and 200),
  pulse integer not null check (pulse between 30 and 220),
  photo_path text,
  measured_at timestamptz not null default now()
);

alter table public.measurements enable row level security;
create policy "users can read own measurements" on public.measurements for select using (auth.uid() = user_id);
create policy "users can insert own measurements" on public.measurements for insert with check (auth.uid() = user_id);
create policy "users can delete own measurements" on public.measurements for delete using (auth.uid() = user_id);

insert into storage.buckets (id, name, public) values ('bp-photos', 'bp-photos', false) on conflict (id) do nothing;
create policy "users can upload own bp photos" on storage.objects for insert with check (bucket_id = 'bp-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users can read own bp photos" on storage.objects for select using (bucket_id = 'bp-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users can delete own bp photos" on storage.objects for delete using (bucket_id = 'bp-photos' and (storage.foldername(name))[1] = auth.uid()::text);
