-- 在 Supabase Dashboard > SQL Editor 執行一次
create table if not exists public.bp_measurements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  systolic integer not null check (systolic between 50 and 300),
  diastolic integer not null check (diastolic between 30 and 200),
  pulse integer not null check (pulse between 30 and 220),
  photo_path text,
  measured_at timestamptz not null default now()
);

alter table public.bp_measurements enable row level security;
drop policy if exists "bp users can read own measurements" on public.bp_measurements;
drop policy if exists "bp users can insert own measurements" on public.bp_measurements;
drop policy if exists "bp users can delete own measurements" on public.bp_measurements;
create policy "bp users can read own measurements" on public.bp_measurements for select using (auth.uid() = user_id);
create policy "bp users can insert own measurements" on public.bp_measurements for insert with check (auth.uid() = user_id);
create policy "bp users can delete own measurements" on public.bp_measurements for delete using (auth.uid() = user_id);

insert into storage.buckets (id, name, public) values ('blood-pressure-photos', 'blood-pressure-photos', false) on conflict (id) do nothing;
drop policy if exists "bp users can upload own photos" on storage.objects;
drop policy if exists "bp users can read own photos" on storage.objects;
drop policy if exists "bp users can delete own photos" on storage.objects;
create policy "bp users can upload own photos" on storage.objects for insert with check (bucket_id = 'blood-pressure-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "bp users can read own photos" on storage.objects for select using (bucket_id = 'blood-pressure-photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "bp users can delete own photos" on storage.objects for delete using (bucket_id = 'blood-pressure-photos' and (storage.foldername(name))[1] = auth.uid()::text);
